[package]
name = "netbaiot-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
schemars = { workspace = true, optional = true }
netbaiot-core.workspace = true
async-trait.workspace = true
bytes.workspace = true
futures-util.workspace = true
hmac.workspace = true
sha2.workspace = true
subtle.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
uuid.workspace = true
reqwest.workspace = true
url.workspace = true
jsonwebtoken = "9.3.1"
fs2 = "=0.4.3"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
atomicwrites = "=0.4.4"

[lints]
workspace = true

[dev-dependencies]
stats_alloc = "=0.1.10"
tokio-rustls.workspace = true
rustls-pemfile.workspace = true

[features]
schema = ["dep:schemars", "netbaiot-core/schema"]
