[package]
name = "netbaiot-device-sdk"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
netbaiot-protocol.workspace = true
futures-core.workspace = true
url.workspace = true
rumqttc.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true

[lints]
workspace = true
